repos:
  - repo: local
    hooks:
      - id: black
        stages: [commit]
        name: black
        language: system
        entry: black
        types: [python]
      - id: isort
        stages: [commit]
        name: isort
        language: system
        entry: isort
        types: [python]
      - id: flake8
        stages: [commit]
        name: flake8
        language: system
        entry: flake8
        types: [python]
      - id: gitlint
        stages: [commit-msg]
        name: gitlint
        description: Validate commit lint
        entry: gitlint --contrib contrib-title-conventional-commits --ignore B1,B5,B6 --msg-filename
        language: system
