# Generated by Django 4.2.8 on 2023-12-06 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Model2",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Text description.",
                        max_length=100,
                        verbose_name="Text comes here",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Model1",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Text description.",
                        max_length=100,
                        verbose_name="Text comes here",
                    ),
                ),
                (
                    "many",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Many description.",
                        null=True,
                        related_name="model1s_many",
                        to="tests.model2",
                        verbose_name="Many",
                    ),
                ),
                (
                    "model2",
                    models.ForeignKey(
                        blank=True,
                        help_text="Model2 description.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model1s",
                        to="tests.model2",
                        verbose_name="Model2",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
