# Generated by Django 3.1.4 on 2020-12-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Model1",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Text description.",
                        max_length=100,
                        verbose_name="Text comes here",
                    ),
                ),
                (
                    "model2",
                    models.ForeignKey(
                        help_text="Model2 description.",
                        on_delete=models.CASCADE,
                        related_name="model1s",
                        to="tests.Model2",
                        verbose_name="Model2",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Model2",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Text description.",
                        max_length=100,
                        verbose_name="Text comes here",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
